[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
pre-build = [
    "dpkg --add-architecture arm64 && apt-get -y update; apt-get -y install libasound2-dev:arm64 libudev-dev:arm64",
]