name: Build for win-x64
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    environment: PROD
    env:
      SERVER_SSL_CA: ${{ secrets.SERVER_SSL_CA }}
      SERVER_SSL_CERT: ${{ secrets.SERVER_SSL_CERT }}
      SERVER_SSL_KEY: ${{ secrets.SERVER_SSL_KEY }}

    steps:
      # Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Install Rust and Cross
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install Cross
        run: cargo install cross

      # Build the project using Cross
      - name: Cross build
        run: cross build --target x86_64-pc-windows-msvc --release --all-features

      # Zip the binary
      - name: Generate tar.gz
        run: |
          cd target/x86_64-pc-windows-msvc/release
          tar cvf - tagoio-relay | gzip > ../../tagoio-relay-win-x64.tar.gz

      # Upload the zip file as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tagoio-relay-win-x64
          path: ./target/x86_64-pc-windows-msvc/tagoio-relay-win-x64.tar.gz
