name: Deploy to DockerHub

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD
    env:
      CARGO_SERVER_SSL_CA: ${{ secrets.SERVER_SSL_CA }}
      CARGO_SERVER_SSL_CERT: ${{ secrets.SERVER_SSL_CERT }}
      CARGO_SERVER_SSL_KEY: ${{ secrets.SERVER_SSL_KEY }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Convert environment variables to Base64
        id: convert_env
        run: |
          echo "CARGO_SERVER_SSL_CA_BASE64=$(echo -n $CARGO_SERVER_SSL_CA | base64)" >> $GITHUB_ENV
          echo "CARGO_SERVER_SSL_CERT_BASE64=$(echo -n $CARGO_SERVER_SSL_CERT | base64)" >> $GITHUB_ENV
          echo "CARGO_SERVER_SSL_KEY_BASE64=$(echo -n $CARGO_SERVER_SSL_KEY | base64)" >> $GITHUB_ENV

      - name: Build and deploy images
        env:
          CARGO_SERVER_SSL_CA_BASE64: ${{ env.CARGO_SERVER_SSL_CA_BASE64 }}
          CARGO_SERVER_SSL_CERT_BASE64: ${{ env.CARGO_SERVER_SSL_CERT_BASE64 }}
          CARGO_SERVER_SSL_KEY_BASE64: ${{ env.CARGO_SERVER_SSL_KEY_BASE64 }}
        run: bash dockerhub.sh ${{ github.event.inputs.version }}
