name: Build for alpine-x64

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  TARGET: x86_64-unknown-linux-gnu
  FILENAME: tagoio-relay-alpine-x64

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD
    env:
      SERVER_SSL_CA: ${{ secrets.SERVER_SSL_CA }}
      SERVER_SSL_CERT: ${{ secrets.SERVER_SSL_CERT }}
      SERVER_SSL_KEY: ${{ secrets.SERVER_SSL_KEY }}

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain and components
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ env.TARGET }}

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Create empty .env file
        run: touch .env

      # Build the modules
      - name: Build Binary
        run: cargo build --verbose --locked --release

      # Run tests
      - name: Run tests
        run: cargo test --verbose
      # Zip the binary
      - name: Generate tar.gz
        run: |
          cd target/release
          tar cvf - tagoio-relay | gzip > ../../${{ env.FILENAME }}.tar.gz

      # Upload the zip file as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILENAME }}
          path: ./${{ env.FILENAME }}.tar.gz
