name: Code Quality
# on: push
on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  stage: prod

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD
    env:
      CARGO_SERVER_SSL_CA: "Code-Quality-Test-CA"
      CARGO_SERVER_SSL_CERT: "Code-Quality-Test-Cert"
      CARGO_SERVER_SSL_KEY: "Code-Quality-Test-Key"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust toolchain and components
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Create empty .env file
        run: touch .env

      - name: Cargo build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Format Check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
